config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "companies#index"
#   resources :users do
#     get 'user_company', on: :collection
#     get 'forgot_password', on: :collection
#     get 'reset_password', on: :collection
#   end
  get '/create_token' , to: 'users#create_token'
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :users , only: [:index ,:edit, :update ] do
    get 'current_users' , on: :collection
    get 'chats' , on: :collection
  end
  
  resources :companies do
    get 'user_company' , on: :collection
    get 'company_by_job_id' , on: :collection
    # get 'search' , on: :collection
  end

  resources :job_applications do 
  	get 'applied_jobs', on: :collection
    get 'application_by_status', on: :collection
  end

  resources :skills do 
    get 'add_skill', on: :collection
    get 'user_skills', on: :collection
    get 'specific_applied_job', on: :member
  end

  resources :jobs do
    get 'current_company_jobs', on: :collection
    get 'top_jobs', on: :collection
    get 'search_jobs_by_company_or_skill_name', on: :collection
    get 'suggested_jobs', on: :collection
  end

#   post '/auth/login', to: 'authentication#login'
#   get '/suggested_jobs', to: 'users#suggested_jobs'
#   get '/top_jobs', to: 'jobs#top_jobs'
#   get '/user_skills', to: 'skills#user_skills'
#   get '/specific_job/:id', to: 'users#specific_job'
#   get '/search_jobs_by_company_or_skill_name', to: 'jobs#search_jobs_by_company_name'
#   get '/application_by_status', to: 'job_applications#application_by_status'
#   get '/company_by_job_id', to: 'companies#company_by_job_id' 
  post 'common/search', to: 'companies#search'
end

app/models/job.rb
class Job < ApplicationRecord
  serialize :required_skills, Array
  belongs_to :company
  # delegate :job_recruiter , to: :company , prefix: true

  has_many :job_applications, dependent: :destroy
  has_many :job_seekers, through: :job_applications,dependent: :destroy

  validates :job_title, uniqueness: { scope: :company_id}, presence: true
  validates :required_skills, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:destroy, :update, :show]

  def index
    @jobs = Job.all
  end
 
  def new
   @job = current_user&.company&.jobs&.new
  end

  def create
    @job = current_user&.company&.jobs&.new(job_params)
    @job.required_skills = params[:job][:required_skills].split(',').map(&:strip) if params[:job][:required_skills].present?
    @job.save!
    flash[:alert] = "job create successfully!"
    redirect_to root_path
  rescue Exception => e
    flash[:alert] = e.message
    render :new , status: 422
  end
  
  def edit
    @job = Job.find_by_id(params[:id])
  end

  def update
 		@job.update!(job_params)

    render json: { message: 'job updated successfuly!' }
  rescue Exception => e
    render json: { errors: e.message } , status: 404
  end

  def destroy
    @job.destroy!
    flash[:alert] = "job deleted successfully!"
    redirect_to request.referer 
  rescue Exception => e
    render json: { errors: e.message }, status: 404
  end
  

  def show
  	@job = Job.find_by_id(params[:id])
  	return render json: { message: 'Job not found' }, status: :not_found unless @job
    render json: @job , status: 200
  end

  def top_jobs
    @jobs = Job.joins(:job_applications).select("jobs.* , count(job_applications.id) as job_application_count").group(:id).order('job_application_count DESC').limit(10)
    render :index
  end

  def current_company_jobs
    company = Company.find_by_id(params[:company_id])
    @jobs = company.jobs
    if @jobs.blank?
      flash[:alert] = "not available jobs"
      redirect_to root_path
    else
      render :index , status: 404
    end
  end

  def search_jobs_by_company_or_skill_name
  	if params[:company_name]
      result = Job.joins(:company).where('companies.company_name like "%?%"', params[:company_name].downcase)
  	elsif params[:skill_name]
  		result = Job.joins(:company).where('jobs.required_skills like "%?%"', params[:skill_name].downcase)
    else
      result = Job.all
  	end
    render json: result , status: 200
  end

  def suggested_jobs
    skills = current_user.skills.select(:skill_name)
    skills.each do |skill|
      @jobs = Job.where('required_skills like ?', "%#{skill.skill_name}%")
    end
    if @jobs.blank?
      flash[:alert] = "jobs are not match for you"
      redirect_to request.referer
    else
      render "jobs/index"
    end
  end
  
  private

  def job_params
    params.require(:job).permit(:job_title, :company_id ,required_skills: [])
  end

  def set_job
    @job = Job.find_by_id(params[:id])
    unless @job
      flash[:alert] = "job not found"
      redirect_to request.referer   
    end   
  end
end

app/views/jobs/_new.html.erb
<div style="text-align: left;">
  <h1 style="font-size: 24px; margin-bottom: 20px;">New Job</h1>

  <%= form_with  model: [ @job, Job.new] , html: { class: 'job-form' } do |job| %>
    <div class="form-group">
      <%= job.label :job_title, style: 'font-weight: bold;' %><br>
      <%= job.text_field :job_title %>
    </div>

    <div class="form-group">
      <%= job.label :required_skills, 'Required Skills (comma-separated)', style: 'font-weight: bold;' %><br>
      <%= job.text_field :required_skills %>
    </div>

    <div class="form-group">
      <%= job.submit "Create" , class: 'btn btn-primary submit-button'%>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<div style="text-align: center;">
  <h1 style="font-size: 24px; margin-bottom: 20px;">New Job</h1>

  <%= form_with model: @job, html: { class: 'job-form' } do |job| %>
    <div class="field" style="margin-bottom: 15px;">
      <%= job.label :job_title, style: 'font-weight: bold;' %><br>
      <%= job.text_field :job_title, class: 'job-input' %>
    </div>

    <div class="field" style="margin-bottom: 15px;">
      <%= job.label :required_skills, 'Required Skills (comma-separated)', style: 'font-weight: bold;' %><br>
      <% if @job.errors.any? %>
        <ul style="list-style-type: none; padding: 0; margin-top: 5px;">
          <% @job.errors[:required_skills].each do |error| %>
            <li style="color: red;"><%= error %></li>
          <% end %>
        </ul>
      <% end %>
      <%= job.text_field :required_skills, class: 'skill-input' %>
    </div>

    <div class="field" style="margin-bottom: 20px;">
      <%= job.submit "Create", class: 'job-button' %>
    </div>
  <% end %>
</div>
 

app/views/jobs/index.html.erb
<div style="text-align: center;">
  <h1 style="font-size: 24px; margin-bottom: 20px;">Listing Jobs</h1>

  <table style="width: 100%; border-collapse: collapse;">
    <thead>
      <tr>
        <th style="border: 1px solid #000; padding: 8px;">Job</th>
        <th style="border: 1px solid #000; padding: 8px;">Required Skills</th>
        <% if current_user.type == "JobRecruiter" %>
          <th style="border: 1px solid #000; padding: 8px;">Job Application</th>
          <th style="border: 1px solid #000; padding: 8px;">Delete Job</th>
        <% else %>
          <th style="border: 1px solid #000; padding: 8px;">Apply job</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td style="border: 1px solid #000; padding: 8px;"><%= job.job_title %></td>
          <td style="border: 1px solid #000; padding: 8px;"><%= job.required_skills %></td>
          <% if current_user.type == "JobRecruiter" %>
            <% data = job.job_applications.ids %>
            <% if data.present? %>
              <td style="border: 1px solid #000; padding: 1px;"><li><%= link_to "job applications", "/job_applications/#{data.first}", style: 'text-decoration: none; color: #007BFF;' %></li></td>
            <% else %>
            <td style="border: 1px solid #000; padding: 8px;"> no applications </td>
            <% end %>
            <td style="border: 1px solid #000; padding: 1px;"><li><%= link_to "delete job", job_path(job.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li></td>
          <% else %>
            <td style="border: 1px solid #000; padding: 8px;"><li><%= link_to "Apply Job", new_job_application_path(job_id: job.id), style: 'text-decoration: none; color: #007BFF;' %></li></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/jobs/new.html.erb
<div style="text-align: center;">
  <h1 style="font-size: 24px; margin-bottom: 20px;">New Job</h1>

  <%= form_with model: @job, html: { class: 'job-form' } do |job| %>
    <div class="form-group">
      <%= job.label :job_title, style: 'font-weight: bold;' %><br>
      <%= job.text_field :job_title %>
    </div>

    <div class="form-group">
      <%= job.label :required_skills, 'Required Skills (comma-separated)', style: 'font-weight: bold;' %><br>
      <%= job.text_field :required_skills %>
    </div>

    <div class="form-group">
      <%= job.submit "Create" , class: 'btn btn-primary submit-button'%>
    </div>
  <% end %>
</div>
 

app/views/jobs/show.html.erb
<h1 style="font-size: 24px; margin-bottom: 20px;">Job Title: <%= @job.job_title %></h1>
 
<p style="font-weight: bold;">Required Skills: <%= @job.required_skills.join(', ') %></p>
<%= link_to "Apply Job", new_job_application_path(:job_id => @job.id), style: 'text-decoration: none; color: #007BFF;' %>