config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "companies#index"
#   resources :users do
#     get 'user_company', on: :collection
#     get 'forgot_password', on: :collection
#     get 'reset_password', on: :collection
#   end
  get '/create_token' , to: 'users#create_token'
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :users , only: [:index ,:edit, :update ] do
    get 'current_users' , on: :collection
    get 'chats' , on: :collection
  end
  
  resources :companies do
    get 'user_company' , on: :collection
    get 'company_by_job_id' , on: :collection
    # get 'search' , on: :collection
  end

  resources :job_applications do 
  	get 'applied_jobs', on: :collection
    get 'application_by_status', on: :collection
  end

  resources :skills do 
    get 'add_skill', on: :collection
    get 'user_skills', on: :collection
    get 'specific_applied_job', on: :member
  end

  resources :jobs do
    get 'current_company_jobs', on: :collection
    get 'top_jobs', on: :collection
    get 'search_jobs_by_company_or_skill_name', on: :collection
    get 'suggested_jobs', on: :collection
  end

#   post '/auth/login', to: 'authentication#login'
#   get '/suggested_jobs', to: 'users#suggested_jobs'
#   get '/top_jobs', to: 'jobs#top_jobs'
#   get '/user_skills', to: 'skills#user_skills'
#   get '/specific_job/:id', to: 'users#specific_job'
#   get '/search_jobs_by_company_or_skill_name', to: 'jobs#search_jobs_by_company_name'
#   get '/application_by_status', to: 'job_applications#application_by_status'
#   get '/company_by_job_id', to: 'companies#company_by_job_id' 
  post 'common/search', to: 'companies#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :omniauthable, omniauth_providers: [:google_oauth2 , :facebook]
  # validates :name, presence: true, length: { minimum: 3, case_sensitive: false }
  # validates :type, presence: true

	# def generate_password_token!
	# 	self.reset_password_token = generate_token
	# 	self.reset_password_sent_at = Time.now.utc
	# 	save!
	# end

	# def password_token_valid?
	# 	(self.reset_password_sent_at + 4.hours) > Time.now.utc
	# end

	# def reset_password!(password)
	# 	self.reset_password_token = nil
	# 	self.password = password
	# 	save!
	# end

	# private

	# def generate_token
	# 	SecureRandom.hex(10)
	# end
	 # def self.from_google(email:)
  #   return nil unless email =~ /@shriffle.com\z/
  #   create_with(name: name).find_or_create_by!(email: email)
  # end
  def self.from_omniauth(auth)
    @user=where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
    end
    return @user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def google_oauth2
    omniauth("Google")
  end

  def facebook
    omniauth("Facebook")
  end

  def omniauth(provider)
    @user = User.from_omniauth(auth)
    if @user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: provider
      return render "users/edit" unless @user.type.present?
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: provider, reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def update_resource(resource, params)
    if resource.provider != nil
      params.delete('current_password')
      resource.password = Devise.friendly_token[0, 20]
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
   def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 skip_before_action :authenticate_user!, only: [:edit , :update]

  def index
    @users = User.all
  end

  def create
    user = User.create!(user_params)
    UserMailer.with(user: user).welcome_email.deliver_now	
    render json: { message: 'user created successfuly!' }, status: :ok
  rescue Exception => e
    render json: { errors: e.message }
  end

  def edit
    @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(update_params)

    sign_in_and_redirect @user
    # render json: { message: 'user updated successfuly!' }, status: :ok
  rescue Exception => e
    # render json: { errors: e.message }
    flash[:alert] = e.message
    redirect_to request.referer
  end

  def destroy
    user = current_user.destroy!
    flash[:alert] = "Your Account Delete Successfully!"
    # render json: { message: 'user deleted successfuly!' }, status: :ok
  rescue Exception => e
    # render json: { errors: e.message }
    flash[:alert] = e.message
    redirect_to request.referer
  end


  def show
    @user = User.find_by_id(params[:id])
    # return render json: { message: 'User Data Not available' } unless user

    # render json: @user
  end

  def current_users
    @users = current_user
    render :index
  end

  def forgot_password
    return render json: {error: 'Email not present'} if params[:email].blank?
    @user = User.find_by(email: params[:email])

    if @user.present?
      @user.generate_password_token!
      UserMailer.with(user: @user).forgot_password_token.deliver_now	
      render json: {status: 'reset link sent to your email'}, status: :ok
    else
      render json: {message: "Email Address Not Found"}, status: :not_found
    end
  end

  def reset_password
    return render json: {error: 'Token not present'} unless token = params[:token]
    return render json: {error: 'email not present'} if params[:email].blank?

    user = User.find_by(reset_password_token: token)

    return render json: {error:  ["Link not valid or expired. Try generating a new link."]}, status: :not_found unless user.present? && user.password_token_valid?
    return render json: {status: 'successfuly!'}, status: :ok if user.reset_password!(params[:password])

    render json: {error: user.errors.full_messages}, status: :unprocessable_entity
  end

  private

  def user_params
    params.permit(:name, :mobile_number, :email, :password, :type)
  end

  def update_params
    params.require(:user).permit(:name, :mobile_number, :type , :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/chats.html.erb
<h1>Chat</h1>
<div class="chat">
  <div class="messages">
    <div class="message">
      <span class="user">User:</span> Let's chat!
    </div>
  </div>
  <form>
    <label for="message">Message:</label>
    <input type="text" id="message" placeholder="Enter your message..." />
    <button type="submit">Send</button>
  </form>
</div>

app/views/users/edit.html.erb
<h2>Select Role</h2>
  <!-- Hidden field for job_id -->
<strong>uid:</strong> <%= @user.uid %></br>
<strong>Email:</strong> <%= @user.email %></br>
<strong>Name:</strong> <%= @user.name %></br>

<!-- Hidden field for status -->
<%= form_with model: @user, url: user_path(@user), method: :patch do |user| %>
  <div class="form">
    <%= user.label :role %><br>
    <%= user.select :type, [:JobRecruiter, :JobSeeker] %>
  </div>

  <div class="form">
    <%= user.submit "continue" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if false %>
	<h1 style="font-size: 24px; margin-bottom: 20px; text-align: center; font-weight: bold;">.....Your Profile.....</h1>

	<p style="font-size: 18px; margin-bottom: 10px; text-align: center; font-weight: bold;">Name: <%= @users.name %></p>
	<p style="font-size: 17px; margin-bottom: 10px; text-align: center; font-weight: bold;">Email: <%= @users.email %></p>
	<p style="font-size: 16px; margin-bottom: 10px; text-align: center; font-weight: bold;">Role: <%= @users.type %></p>
	<p style="font-size: 16px; margin-bottom: 10px; text-align: center; font-weight: bold;"><%= link_to "Edit Your Profile", edit_user_registration_path(@users)%></p>
	<p style="font-size: 16px; margin-bottom: 10px; text-align: center; font-weight: bold;"><%= link_to "Delete my account", registration_path(@users), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %></p>
<% end %>
<section class="vh-100" style="background-color: darkgrey;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar" class="rounded-circle img-fluid" style="height: 250px;">
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Your Profile</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Email</h6>
                    <p class="text-muted"><%= @users.email %></p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Name</h6>
                    <p class="text-muted"><%= @users.name %></p>
                  </div>
                </div>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Role</h6>
                    <p class="text-muted"><%= @users.type %></p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Status</h6>
                    <p class="text-muted">Active</p>
                  </div>
                </div>
                <div class="d-flex justify-content-start">
                  <%= link_to "Delete my account", registration_path(@users), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %>
                  <%= link_to "Edit Your Profile", edit_user_registration_path(@users)%>
                  <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<h1 style="font-size: 24px; margin-bottom: 20px;">User Name: <%= @user.name %></h1>
 
<p style="font-weight: bold;">Email: <%= @user.email %></p>
<p style="font-weight: bold;">Type: <%= @user.type %></p>
<br/>