config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "companies#index"
#   resources :users do
#     get 'user_company', on: :collection
#     get 'forgot_password', on: :collection
#     get 'reset_password', on: :collection
#   end
  get '/create_token' , to: 'users#create_token'
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :users , only: [:index ,:edit, :update ] do
    get 'current_users' , on: :collection
    get 'chats' , on: :collection
  end
  
  resources :companies do
    get 'user_company' , on: :collection
    get 'company_by_job_id' , on: :collection
    # get 'search' , on: :collection
  end

  resources :job_applications do 
  	get 'applied_jobs', on: :collection
    get 'application_by_status', on: :collection
  end

  resources :skills do 
    get 'add_skill', on: :collection
    get 'user_skills', on: :collection
    get 'specific_applied_job', on: :member
  end

  resources :jobs do
    get 'current_company_jobs', on: :collection
    get 'top_jobs', on: :collection
    get 'search_jobs_by_company_or_skill_name', on: :collection
    get 'suggested_jobs', on: :collection
  end

#   post '/auth/login', to: 'authentication#login'
#   get '/suggested_jobs', to: 'users#suggested_jobs'
#   get '/top_jobs', to: 'jobs#top_jobs'
#   get '/user_skills', to: 'skills#user_skills'
#   get '/specific_job/:id', to: 'users#specific_job'
#   get '/search_jobs_by_company_or_skill_name', to: 'jobs#search_jobs_by_company_name'
#   get '/application_by_status', to: 'job_applications#application_by_status'
#   get '/company_by_job_id', to: 'companies#company_by_job_id' 
  post 'common/search', to: 'companies#search'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :job_recruiter , class_name: 'JobRecruiter' , foreign_key: 'job_recruiter_id'
  has_many :jobs, dependent: :destroy

  validates :company_name , uniqueness: { scope: :job_recruiter_id}
  validates :address, :contact, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:update, :destroy]
  def index
    if current_user.type == "JobRecruiter" && current_user.company.present?
      @company = current_user.company
      render :show
    else
      @companies = Company.all
    end
  end

  def new
    @company = current_user.create_company
  end

  def create
    @company = current_user.create_company!(company_params)
    redirect_to root_path
  rescue Exception => e
    render :new , status: 422
  end

  def destroy
    @company.destroy!
    render json: { message: 'company deleted successfully!' }
  rescue Exception => e
    render json: { errors: e.message }
  end

  def edit
    @company = Company.find_by_id(params[:id])
  end

  def update
    @company.update!(company_params)
    render json: { message: 'company updated successfuly!'}
  rescue Exception => e
    render :edit , status: 422
  end

  def show
  	@company = Company.find_by_id(params[:id])
  end

  def company_by_job_id
  	job = Job.find_by_id(params[:id])
  	return render json: { message: "job not available"}, status: 404 unless job
  	render json: job.company , status: 200
  end

  def user_company
    @company = current_user.company
    return render json: { message: "you have not create any company" } unless @company.present?

    render json: @company
  end

  def search
  	query = params[:search]
    return flash[:notice] =  "not available"if query.blank?
  	user = User.where('name like ?', "%#{query}%")
    @user = user.first
  	if @user.blank?
      @companies = Company.where('company_name like ?',"%#{query}%")  
      if @companies.blank?
  		  @skills = Skill.where('skill_name like ?',"%#{query}%")
  		  if @skills.blank?
  		    @jobs = Job.where('job_title like ?',"%#{query}%")
          if @jobs.blank?
            redirect_to companies_path
          else
            render "jobs/index"
          end
        else
          render "skills/index"
  		  end
      else
        render "companies/index"
  		end
    else
      render "users/show"
  	end
  end
 
  private

  def company_params
    params.require(:company).permit(:job_recruiter_id, :company_name, :address, :contact)
  end

  def set_company
    @company = current_user.company
  end
end

app/views/companies/edit.html.erb
<h1 style="font-size: 24px; margin-bottom: 20px;">New Company</h1>

<%= form_with model: @company, html: { style: 'margin-top: 20px;' } do |company| %>
  <div class="field" style="margin-bottom: 10px;">
    <%= company.label :company_name, style: 'font-weight: bold;' %><br>
    <%= company.text_field :company_name, style: 'width: 100%; padding: 5px;' %> 
  </div>

  <div class="field" style="margin-bottom: 10px;">
    <%= company.label :address, style: 'font-weight: bold;' %><br>
    <%= company.text_field :address, style: 'width: 100%; padding: 5px;' %>
  </div>

  <div class="field" style="margin-bottom: 10px;">
    <%= company.label :contact, style: 'font-weight: bold;' %><br>
    <%= company.text_field :contact, style: 'width: 100%; padding: 5px;' %>
  </div>

  <div class="field">
    <%= company.submit "Create", style: 'background-color: #007BFF; color: #fff; padding: 10px 20px; border: none; cursor: pointer;' %>
  </div>
<% end %>

app/views/companies/index.html.erb
<nav class="navbar fixed-bottom navbar-light" style="background-color: lightblue">
     <ul class="nav">
      <% if current_user.type == "JobRecruiter" %>
        <li class="nav-item"><a class="nav-link active" href="skills/new">Create Skill</a></li>
        <% if current_user.company.blank? %>
          <li class="nav-item"><a class="nav-link active" href="companies/new">Create New Company</a></li>
        <% end %>
      <% else current_user.type == "JobSeeker" %>
        <li class="nav-item"><a class="nav-link active" href="skills/add_skill">Add Skill</a></li>
        <% if current_user.job_applications.applied.present? %>
          <li class="nav-item"><a class="nav-link active" href="job_applications/applied_jobs">Applied Applications</a></li>
        <% end  %>
          <li class="nav-item"><a class="nav-link active" href="skills/user_skills">Your Skills</a></li>
          <li class="nav-item"><a class="nav-link active" href="jobs/suggested_jobs">Jobs For You</a></li>
      <% end %>
    </ul>
</nav>
<h1 style="font-size: 24px; margin-bottom: 20px;">Company</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <% unless current_user.type == "JobRecruiter" && current_user.company.blank? %>
        <% @companies.each do |company| %>
          <%= link_to company.company_name, company, style: 'text-decoration: none; color: #007BFF;' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<h1 style="font-size: 24px; margin-bottom: 20px;">New Company</h1>

<%= form_with model: @company, html: { style: 'margin-top: 20px;' } do |company| %>
  <div class="form-check">
    <%= company.label :company_name, class: 'font-weight: bold;' %><br>
    <%= company.text_field :company_name%> 
  </div>

  <div class="form-check">
    <%= company.label :address, style: 'font-weight: bold;' %><br>
    <%= company.text_field :address %>
  </div>

  <div class="form-check">
    <%= company.label :contact, style: 'font-weight: bold;' %><br>
    <%= company.text_field :contact %>
  </div>

  <div class="btn-outline-success">
    <%= company.submit "Create" , class: 'btn btn-primary submit-button' %>
  </div>
<% end %>

app/views/companies/show.html.erb
<nav class="navbar navbar-expand-sm " style="background-color: lightgrey">
	<a class="navbar-brand" href="">Home</a>
	<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
     Menu
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
	  <li class="dropdown-item"><%= link_to "Jobs", current_company_jobs_jobs_path(:company_id => @company.id) %>
	<% if current_user.type == "JobRecruiter" %>
	  <% if current_user.company.present? %>
	    <li class="dropdown-item"><%= link_to "Create Skill", new_skill_path%></li>   
	    <!-- <li class="dropdown-item"><%= link_to "Create Job", new_job_path%></li>    -->
	    <li class="dropdown-item"><%= link_to "See Skills", skills_path %></li>
	    <li class="dropdown-item"><%= link_to "Top Jobs", top_jobs_jobs_path%></li>
	  <% end %>
	<% end %>
</nav>
<h1 style="font-size: 24px; margin-bottom: 20px;">Company Name: <%= @company.company_name %></h1>
 
<p style="font-weight: bold;">Address: <%= @company.address %></p>
<p style="font-weight: bold;">Contact: <%= @company.contact %></p>
<p style="font-weight: bold;">Recruiter Name: <%= @company.job_recruiter.name %></p>
<br/>
<h2> Create Job </h2>
<%= render "jobs/new" %>