config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "companies#index"
#   resources :users do
#     get 'user_company', on: :collection
#     get 'forgot_password', on: :collection
#     get 'reset_password', on: :collection
#   end
  get '/create_token' , to: 'users#create_token'
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :users , only: [:index ,:edit, :update ] do
    get 'current_users' , on: :collection
    get 'chats' , on: :collection
  end
  
  resources :companies do
    get 'user_company' , on: :collection
    get 'company_by_job_id' , on: :collection
    # get 'search' , on: :collection
  end

  resources :job_applications do 
  	get 'applied_jobs', on: :collection
    get 'application_by_status', on: :collection
  end

  resources :skills do 
    get 'add_skill', on: :collection
    get 'user_skills', on: :collection
    get 'specific_applied_job', on: :member
  end

  resources :jobs do
    get 'current_company_jobs', on: :collection
    get 'top_jobs', on: :collection
    get 'search_jobs_by_company_or_skill_name', on: :collection
    get 'suggested_jobs', on: :collection
  end

#   post '/auth/login', to: 'authentication#login'
#   get '/suggested_jobs', to: 'users#suggested_jobs'
#   get '/top_jobs', to: 'jobs#top_jobs'
#   get '/user_skills', to: 'skills#user_skills'
#   get '/specific_job/:id', to: 'users#specific_job'
#   get '/search_jobs_by_company_or_skill_name', to: 'jobs#search_jobs_by_company_name'
#   get '/application_by_status', to: 'job_applications#application_by_status'
#   get '/company_by_job_id', to: 'companies#company_by_job_id' 
  post 'common/search', to: 'companies#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkedInJobPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js' %>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js' %>
    <%= stylesheet_link_tag "application","data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="bg-image" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg'); height: auto;">
    <%- if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightgrey">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item" ><%= link_to "Home", root_path , style: 'color: black; padding: 10px;' %></li>
              <% if current_user.type == "JobRecruiter" %>  
                <li class="nav-item"><%= link_to "Create skill", new_skill_path , style: 'color: black; padding: 10px;'%></li>
                <% if current_user.company.blank? %>
                  <li class="nav-item"><%= link_to "Create company", new_comapny_path , style: 'color: black; padding: 10px;'%></li>
                <% end %>
              <% end %>
              <li class="nav-item"><%= form_tag common_search_path, method: :post do %><%= text_field_tag :search , params[:search] %><%= submit_tag "Search", name: nil %><% end %></li>
            </ul>
          </div>

          <% if request.path == "/companies/#{params[:id]}" || "/"%>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
               Menu
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <% if current_user.type == "JobRecruiter" %>
                  <% if current_user.company.present? %>
                    <li class="dropdown-item"><%= link_to "Create Skill", new_skill_path , style: 'color: black;'%></li>   
                    <li class="dropdown-item"><%= link_to "See Skills", skills_path , style: 'color: black;'%></li>
                    <li class="dropdown-item"><%= link_to "Top Jobs", top_jobs_jobs_path , style: 'color: black;'%></li>
                  <% end %>
                <% else %>
                  <li class="dropdown-item"><%= link_to "Add Skill", add_skill_skills_path , style: 'color: black;'%></li>
                  <% if current_user.job_applications.applied.present? %>
                    <li class="dropdown-item"><%= link_to "Applied Applications", applied_jobs_job_applications_path, style: 'color: black;'%></li>
                  <% end  %>
                  <li class="dropdown-item"><%= link_to "Your Skills", user_skills_skills_path , style: 'color: black;'%></li>
                  <li class="dropdown-item"><%= link_to "Jobs For You", suggested_jobs_jobs_path , style: 'color: black;'%></li>
                <% end %>
              <li class="dropdown-item"><%= link_to "Chat", chats_users_path , style: 'color: black;'%></li>
              <li class="dropdown-item"><%= link_to "Profile", current_users_users_path , style: 'color: black;'%></li>
              <li class="dropdown-item"><%= link_to "Sign out", users_sign_out_path , style: 'color: black;'%></li>
              </ul>
            </div>
          <% end%>
        </div>
      </nav>
    <% end %>
    <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>
    <% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <%= yield %>
    <%- if user_signed_in? %>
      <%= link_to "Back", :back , style: 'font-size: 18px' %>
    <% end %>
  </div>
  </body>
</html>